spring.modulith:
  republish-outstanding-events-on-restart: true
  events.jdbc.schema-initialization.enabled: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cqrs_db
    username: test_user
    password: test_pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: create
