
spring:
  cloud:
    stream:
      bindings:
        enrichLogMessage-in-0:
          destination: input-topic
          group: test-group
        enrichLogMessage-out-0:
          destination: output-topic

server:
  port: 0
management:
  health:
    binders:
      enabled: true